name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths-ignore:
      # Ignore changes to documentation and workflow files
      - '**.md'
      - '.github/workflows/**'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:  # Manual trigger will still work

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for checking changes
      
    - name: Check for application changes
      id: check_changes
      run: |
        # Check if this is a manual trigger
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Manual trigger, proceeding with build"
          echo "build_needed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get the commit count to handle repositories with only one commit
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Total commits in repository: $COMMIT_COUNT"
        
        # For repositories with only one commit, always build
        if [[ "$COMMIT_COUNT" -le 1 ]]; then
          echo "Repository has only one commit, proceeding with build"
          echo "build_needed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get the list of changed files between the last two commits
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD || echo "all")
        echo "Changed files:"
        echo "$CHANGED_FILES"
        
        # If we couldn't get changed files, proceed with build
        if [[ "$CHANGED_FILES" == "all" ]]; then
          echo "Could not determine changed files, proceeding with build"
          echo "build_needed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if any application files were changed
        if echo "$CHANGED_FILES" | grep -qE '(src/|public/|static/|\.py$|\.js$|\.html$|\.css$|package\.json|package-lock\.json|requirements\.txt|pyproject\.toml|Dockerfile|\.dockerignore)'; then
          echo "Application files changed, proceeding with build"
          echo "build_needed=true" >> $GITHUB_OUTPUT
        else
          echo "No application files changed, skipping build"
          echo "build_needed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Set up Docker Buildx
      if: steps.check_changes.outputs.build_needed == 'true'
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      if: steps.check_changes.outputs.build_needed == 'true'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      if: steps.check_changes.outputs.build_needed == 'true'
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha,format=long
          type=ref,event=branch
          latest
          
    - name: Build and push Docker image
      if: steps.check_changes.outputs.build_needed == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Skip build notification
      if: steps.check_changes.outputs.build_needed != 'true'
      run: |
        echo "Docker build skipped because no application files were changed."
        echo "To force a build, use the workflow_dispatch trigger."