name: Pull Request Check

on:
  pull_request:
    branches: [ main ]

jobs:
  application-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start application in background
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Give the application time to start
        
    - name: Check if application is running
      run: |
        # Check if the home page is accessible
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ | grep 200
        
        # Check if the health endpoint is accessible
        response=$(curl -s http://localhost:8000/health)
        echo $response
        if [[ $response != *"healthy"* ]]; then
          echo "Health check failed"
          exit 1
        fi